services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:80"
    environment:
      - APP_SERVICE_URL=${APP_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=80
  app:
    build: ./services/app
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4002
      - NODE_ENV=production
  user:
    build: ./services/user
    ports:
      - "4001:4001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=4001
